#cloudbuild.yaml
steps:
- name: 'gcr.io/cloud-builders/docker'
  env:
  - 'PORT=${_PORT}'
  - 'DOMAIN_SERVER=${_DOMAIN_SERVER}'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$IMAGE_NAME', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/$IMAGE_NAME']
