#cloudbuild.yaml
steps:
- name: 'gcr.io/cloud-builders/docker'
  env:
  - 'PORT=${_PORT}'
  - 'DOMAIN_SERVER=${_DOMAIN_SERVER}'
  args: ['build', 'tag', 'ghost:latest', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA', '.']
images: ['gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
