#cloudbuild.yaml
steps:
- name: 'gcr.io/cloud-builders/docker'
  env:
  - 'PORT=${_PORT}'
  - 'DOMAIN_SERVER=${_DOMAIN_SERVER}'
  args: ['build', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  env:
  - 'PORT=${_PORT}'
  - 'DOMAIN_SERVER=${_DOMAIN_SERVER}'
  args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
images: ['gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
